name 'java'
maintainer 'Stoyan Stoyanov'
maintainer_email 'stoyanoff.s@gmail.com'
license 'all_rights'
description 'Installs/Configures java'
long_description 'Installs/Configures java'
version '0.1.0'
