name 'apache2'
maintainer 'Stoyan Stoyanov'
maintainer_email 'stoyanoff.s@gmail.com'
license 'all_rights'
description 'Installs/Configures apache2'
long_description 'Installs/Configures apache2'
version '0.1.0'
