---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: '12.5.1'

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[logstash::default]
    attributes:
  - name: forwarder
    run_list:
      - recipe[logstash::forwarder]
    attributes:
