name 'logstash'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures logstash'
long_description 'Installs/Configures logstash'
version '0.1.0'
