---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: '12.5.1'

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[kibana::default]
    attributes: { kibana: { version: '4.2.0-linux-x64' } }
