name 'kibana'
maintainer 'Stoyan Stoyanov'
maintainer_email 'stoyanoff.s@gmail.com'
license 'all_rights'
description 'Installs/Configures kibana'
long_description 'Installs/Configures kibana'
version '0.1.0'
